jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  globalNodeProperties:
  - envVars:
      env:
      - key: VARIABLE1
        value: foo
      - key: VARIABLE2
        value: bar
  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp2"
credentials:
  system:
    domainCredentials:
      - domain:
          name: "test.com"
          description: "test.com domain"
          specifications:
            - hostnameSpecification:
                includes: "*.test.com"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "username1"
              username: root1
              password: "${SUDO_PASSWORD}"
          - usernamePassword:
              scope: GLOBAL
              id: "username2"
              username: root2
              password: "${SUDO_PASSWORD}"
          - usernamePassword:
              scope: GLOBAL
              id: "username3"
              username: root3
              password: "${SUDO_PASSWORD}"
tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git
  nodejs:
    installations:
      - name: "NodeJS Latest"
        home: "" #required until nodejs-1.3.4 release (JENKINS-57508)
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "12.11.1"
                    npmPackagesRefreshHours: 48 #default is 72
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/mkrzyzanowski/blog-001.git' }
                        branch '*/docker-for-mac'
                        extensions {}
                    }
                  }
              }
          }
      }